config/routes.rb
Rails.application.routes.draw do
  root "spots#index"

  get "/:lat/:lng", to: 'spots#genMap'

  get "spots/:spot_id", to: 'spots#spot'

  post "go/:lat/:lng/:spot_id", to: 'spots#go'

end

app/models/visit_log.rb
class VisitLog < ActiveRecord::Base
end

app/models/vist_log.rb
class VistLog < ActiveRecord::Base
end

app/controllers/go_controller.rb
class GoController < ApplicationController
  def index
    require 'mysql2'

    seasons = [4, 4, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4]

    spot_id = params[:spot_id]
    lat     = params[:lat]
    lng     = params[:lng]
    weather = 1
    group   = 1
    season  = seasons[Date.today.month - 1]

    client  = Mysql2::Client.new(:host => "localhost", :username => "root", :database => 'bashit_db')
    client.query("INSERT INTO visit_logs (spot_id, weather, group_kind, season, latlng) VALUES (#{spot_id}, #{weather}, #{group}, #{season}, Point(#{lat}, #{lng}))")

    @latlng = client.query("SELECT X(latlng) as lng, Y(latlng) as lat from spots where id = #{spot_id}");
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]

  # GET /spots
  # GET /spots.json
  def index
      puts "index"
  end

  def genMap
      puts "緯度・経度を取得してアルゴリズムをかけてスコアが高い順に返す"
      params[:lat]
      params[:lng]
      # SQL
      client  = ActiveRecord::Base.connection

      # TODO: WHERE句の末尾の3を変更
      @results = client.select_rows("
        SELECT
          *,
          GLength(GeomFromText(CONCAT('LineString(139.0808219 35.1429357,', X(latlng), ' ', Y(latlng),')'))) * 112.12 / 5 As dist
        FROM spots
        WHERE
          GLength(GeomFromText(CONCAT('LineString(139.0808219 35.1429357,', X(latlng), ' ', Y(latlng),')'))) * 112.12 / 5 < 3
      ")

      # ビューに渡す値
      puts @results.to_a
      render :index
  end

  def spot
      # puts "スポットの詳細表示"
      # params[:spot_id]
      require 'mysql2'

      client  = Mysql2::Client.new(:host => "localhost", :username => "root", :database => 'bashit_db')
      @spot   = client.query("SELECT * FROM spots WHERE id = #{params[:spot_id]}").first
      render :spot
  end

  def go
      # 行く」ボタンを押した後のページ
      require 'mysql2'

      seasons = [4, 4, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4]

      spot_id = params[:spot_id]
      lat     = params[:lat]
      lng     = params[:lng]
      weather = 1
      group   = 1
      season  = seasons[Date.today.month - 1]

      client  = Mysql2::Client.new(:host => "localhost", :username => "root", :database => 'bashit_db')
      client.query("INSERT INTO visit_logs (spot_id, weather, group_kind, season, latlng) VALUES (#{spot_id}, #{weather}, #{group}, #{season}, Point(#{lat}, #{lng}))")

      @latlng = client.query("SELECT X(latlng) as lng, Y(latlng) as lat from spots where id = #{spot_id}");

      render :go
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    require 'mysql2'

    client  = Mysql2::Client.new(:host => "localhost", :username => "root", :database => 'bashit_db')

    # TODO: WHERE句の末尾の3を変更
    @results = client.query("
      SELECT
        *,
        GLength(GeomFromText(CONCAT('LineString(139.0808219 35.1429357,', X(latlng), ' ', Y(latlng),')'))) * 112.12 / 5 As dist
      FROM spots
      WHERE
        GLength(GeomFromText(CONCAT('LineString(139.0808219 35.1429357,', X(latlng), ' ', Y(latlng),')'))) * 112.12 / 5 < 3
    ")
  end

  def show
  end
end

app/controllers/visit_logs_controller.rb
class VisitLogsController < ApplicationController
  before_action :set_visit_log, only: [:show, :edit, :update, :destroy]

  # GET /visit_logs
  # GET /visit_logs.json
  def index
    @visit_logs = VisitLog.all
  end

  # GET /visit_logs/1
  # GET /visit_logs/1.json
  def show
  end

  # GET /visit_logs/new
  def new
    @visit_log = VisitLog.new
  end

  # GET /visit_logs/1/edit
  def edit
  end

  # POST /visit_logs
  # POST /visit_logs.json
  def create
    @visit_log = VisitLog.new(visit_log_params)

    respond_to do |format|
      if @visit_log.save
        format.html { redirect_to @visit_log, notice: 'Visit log was successfully created.' }
        format.json { render :show, status: :created, location: @visit_log }
      else
        format.html { render :new }
        format.json { render json: @visit_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visit_logs/1
  # PATCH/PUT /visit_logs/1.json
  def update
    respond_to do |format|
      if @visit_log.update(visit_log_params)
        format.html { redirect_to @visit_log, notice: 'Visit log was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit_log }
      else
        format.html { render :edit }
        format.json { render json: @visit_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visit_logs/1
  # DELETE /visit_logs/1.json
  def destroy
    @visit_log.destroy
    respond_to do |format|
      format.html { redirect_to visit_logs_url, notice: 'Visit log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit_log
      @visit_log = VisitLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_log_params
      params.require(:visit_log).permit(:spot_id, :weather, :group_kind, :integer, :season, :integer)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def count
    require 'mysql2'

    client  = Mysql2::Client.new(:host => "localhost", :username => "root", :database => 'bashit_db')

    seasons = [4, 4, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4]

    @results = client.query("SELECT spot_id, count(*) As visits FROM vist_log WHERE season = #{seasons[Date.today.month - 1]} GROUP BY spot_id")
  end
end

app/controllers/vist_logs_controller.rb
class VistLogsController < ApplicationController
	def change	
   end
end

app/helpers/go_helper.rb
module GoHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/visit_logs_helper.rb
module VisitLogsHelper
end

app/helpers/vist_logs_helper.rb
module VistLogsHelper
end

app/views/go/index.html.erb
<h1>Go#index</h1>
<p>Find me in app/views/go/index.html.erb</p>

<%= @latlng %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baship</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/done.html.erb
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <%= asset_path('style.css') %>
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">ビシっと</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">展開後の選択肢がここに入れられる</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <p class="text-center">
            マップページ
        </p>
        <!--
        選んだ行き先の地図を開く
        https://www.google.co.jp/maps?q=緯度,軽度

        ↓で「おんやど恵」の位置にピンが立つ
        <a href="http://maps.google.com/maps?q=35.1429357,139.0786332">マップを開く</a>
        -->
        <p class="text-center">
            <a href="http://maps.google.com/maps?q=35.1429357,139.0786332">マップを開く</a>
        </p>
    </div>

    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <%= asset_path('choose.js') %>

</body>

</html>

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/go.html.erb
<!--[if lt IE 8]> <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p> <![endif]-->

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">ビシっと</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">展開後の選択肢がここに入れられる</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <p class="text-center">
        マップページ
    </p>
    <!--
        選んだ行き先の地図を開く
        https://www.google.co.jp/maps?q=緯度,軽度

        ↓で「おんやど恵」の位置にピンが立つ
        <a href="http://maps.google.com/maps?q=35.1429357,139.0786332">マップを開く</a>
        -->
    <p class="text-center">
      <a href="http://maps.google.com/maps?q=<%= @latlng[:lat] %>,<%= @latlng[:lng] %>">マップを開く</a>
    </p>
</div>

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

app/views/spots/index.html.erb
<!--[if lt IE 8]> <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p> <![endif]-->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">ビシっと</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">展開後の選択肢がここに入れられる</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <p>
        <form action="/" method="POST" name="form">
            <div class="input-group">
                <span class="input-group-addon" id="sizing-addon1">晴れ 07月10日（日） 2:36 -
                </span>
                <input type="text" class="form-control" placeholder="5:36" aria-describedby="sizing-addon1" name="empty_time">
                <input type="hidden" id="lat_form" name="lat" value="">
                <input type="hidden" id="lng_form" name="lng" value="">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">更新</button>
                </span>
            </div>
        </form>
    </p>
    <div class="panel panel-default" id="first-place">
        <div class="panel-heading">
            <h3 class="panel-title"><%= @results[0][1] %></h3>
        </div>
        <div class="panel-body">
            <p class="text-right">
                35
                <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            </p>
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="https://placehold.jp/240x180.png" width="80">
                    </a>
                </div>
                <div class="media-body">
                    <p>
                        <%= @results[1][2] %>
                    </p>
                </div>
            </div>
            <form action="" method="post" name="go-button">
                <!-- value = spot_id -->
                <input type="hidden" name="spot_id" value="1">
                <!-- 緯度・経度  -->
                <input type="hidden" id="lat_go-button" name="lat" value="">
                <input type="hidden" id="lng_go-button" name="lng" value="">
                <button type="button" class="btn btn-default pull-right go-button" aria-label="Left Align" onclick="go(1)">
                    行く
                    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                </button>
            </form>
        </div>
        <div class="panel-footer">
            片道：<%= @results[0][6] * 60 %>分、滞在時間：2時間
        </div>
    </div>
    <div class="panel panel-default" id="second-place">
        <div class="panel-heading">
            <h3 class="panel-title"><%= @results[1][1] %></h3>
        </div>
        <div class="panel-body">
            <p class="text-right">
                35
                <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
            </p>
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object" src="https://placehold.jp/240x180.png" width="80">
                    </a>
                </div>
                <div class="media-body">
                    <p>
                        <%= @results[1][2] %>
                    </p>
                </div>
            </div>
            <form action="" method="post" name="go-button">
                <!-- value = spot_id をバインド -->
                <input type="hidden" name="spot_id" value="1">
                <!-- 緯度・経度  -->
                <input type="hidden" id="lat_go-button" name="lat" value="">
                <input type="hidden" id="lng_go-button" name="lng" value="">
                <button type="button" class="btn btn-default pull-right go-button" aria-label="Left Align" onclick="go(2)">
                    行く
                    <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                </button>
            </form>
        </div>
        <div class="panel-footer">
            片道：<%= @results[1][6] * 60 %>分、滞在時間：2時間
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/1.0.0/anime.min.js"></script>
<%= javascript_include_tag 'location' %>
<%= javascript_include_tag 'choose' %>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @spot.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @spot.body %>
</p>

<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to 'Back', spots_path %>

app/views/spots/spot.html.erb
spots/show.html.erb
スポットの詳細表示

<%= @spot %>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>

<% @results.each do |row| %>
  <%= row %>
<% end %>

app/views/top/show.html.erb
<h1>Top#show</h1>
<p>Find me in app/views/top/show.html.erb</p>

app/views/visit_logs/_form.html.erb
<%= form_for(@visit_log) do |f| %>
  <% if @visit_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit_log.errors.count, "error") %> prohibited this visit_log from being saved:</h2>

      <ul>
      <% @visit_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spot_id %><br>
    <%= f.number_field :spot_id %>
  </div>
  <div class="field">
    <%= f.label :weather %><br>
    <%= f.number_field :weather %>
  </div>
  <div class="field">
    <%= f.label :group_kind %><br>
    <%= f.text_field :group_kind %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :season %><br>
    <%= f.text_field :season %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visit_logs/edit.html.erb
<h1>Editing Visit Log</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit_log %> |
<%= link_to 'Back', visit_logs_path %>

app/views/visit_logs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Visit Logs</h1>

<table>
  <thead>
    <tr>
      <th>Spot</th>
      <th>Weather</th>
      <th>Group kind</th>
      <th>Integer</th>
      <th>Season</th>
      <th>Integer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visit_logs.each do |visit_log| %>
      <tr>
        <td><%= visit_log.spot_id %></td>
        <td><%= visit_log.weather %></td>
        <td><%= visit_log.group_kind %></td>
        <td><%= visit_log.integer %></td>
        <td><%= visit_log.season %></td>
        <td><%= visit_log.integer %></td>
        <td><%= link_to 'Show', visit_log %></td>
        <td><%= link_to 'Edit', edit_visit_log_path(visit_log) %></td>
        <td><%= link_to 'Destroy', visit_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visit log', new_visit_log_path %>

app/views/visit_logs/new.html.erb
<h1>New Visit Log</h1>

<%= render 'form' %>

<%= link_to 'Back', visit_logs_path %>

app/views/visit_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spot:</strong>
  <%= @visit_log.spot_id %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @visit_log.weather %>
</p>

<p>
  <strong>Group kind:</strong>
  <%= @visit_log.group_kind %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @visit_log.integer %>
</p>

<p>
  <strong>Season:</strong>
  <%= @visit_log.season %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @visit_log.integer %>
</p>

<%= link_to 'Edit', edit_visit_log_path(@visit_log) %> |
<%= link_to 'Back', visit_logs_path %>